### ISSUE TITLE
What does TTF to OTF do?

### ISSUE THREAD

**Issue by elmimmo** [pettarin/glyphIgo#10]
Considering both TTF and OTF are file extensions for OpenType, what does the conversion do? TTF is allegedly usually used for OpenType fonts with TrueType outlines while OTF is for OpenType fonts with PostScript outlines. Is converting from one outline format to the other what it does?

**Comment by pettarin** [comment]
I honestly have no idea --- I regret I have never had time to study what the fontforge lib does behind the scenes.

**Comment by khaledhosny** [comment]
Converting from quadratic (TrueType) curves to cubic (PostScript) curves is the gist of it, with some other small changes to other font tables.

**Comment by elmimmo** [comment]
I wonder about who would need this feature, but anyway, thank you for the explanation.
